<?php
return [
    'app_name'=>'b6wang.com',
    'app_keywords'=>['b6平台','b6娱乐'],
    'search_type'=>'video',
    'search_keyword'=>'做菜',
    'title_keywords'=>['视频','教程','xx0oo','b6平台','b6娱乐','b6'],
    //评论
    'comment_max'=>10,
    'comment_min'=>8,
    //发布
    'title_text'=>['手把手教你','一起来学习吧','每天进步一点点','实践是最好的学习方法'],
    'fields_filter'=>['content'=>'','comment'=>''],
    //定时
    'crontab_category_id_max'=>12,
    'crontab_category_id_min'=>1,
    'crontab_num_max'=>1,
    'crontab_num_min'=>1,
    'crontab_comment'=>10,
];