<?php
return [
    'app_name'=>'sincai2010.com',
    'app_keywords'=>['杏彩平台','杏彩主管','杏彩注册','杏彩网址','杏彩登陆'],
    'search_type'=>'video',
    'search_keyword'=>'鱼',
    'title_keywords'=>['视频','高清','xx0oo','杏彩平台','杏彩主管','杏彩','杏彩注册'],
    //评论
    'comment_max'=>5,//最大页数
    'comment_min'=>15,//最小的评论数
    //发布
    'title_text'=>['快来看看','欣赏一下','好有趣呀',''],
    'fields_filter'=>['content'=>'','comment'=>''],
    //定时
    'crontab_category_id_max'=>1,
    'crontab_category_id_min'=>1,
    'crontab_num_max'=>1,
    'crontab_num_min'=>1,
    'crontab_comment'=>6,
];